### PR TITLE
Fixed #75: Pick the correct size of the icon from a .ico file.

### LINKED ISSUE #75: Downscaling from the maximum icon size instead of picking the correct icon size from an icon package (.ico file).
I have an icon package with icons of 3 sizes: 64x64, 32x32, 16x16, the icon must be 16x16 in my case, but is always picked an icon with a higher resolution then downscaled to 16x16, even if i have added explicitly a 16x16 icon.

The downscaling degrades my icon, making it blurry, for example my 16x16 uses a cross of 1 pixel, but it displays a wrong downscaled icon that has a blurry 2 pixel cross.

tray

The only solution is to use a .ico file with only a 16x16 icon size, but this way doesn't support monitors with higher resolution that will upscale the 16x16.

tray2

### PR DESCRIPTION
**Pull request by devpelux**
As explained in #75, if a .ico file with multiple icons is used, the wrong size of the icon is picked and downscaled to the requested size.

This PR fixed that problem by sending the requested icon size when creating the icon.

Downscaled wrong icon:  
tray

Right icon:  
tray2

Tested on Windows 11 with .NET 6.0.

### CODE REVIEW

**Comment by devpelux** [comment]
> The reference assemblies for .NETFramework,Version=v4.5 were not found.

I think is because net 4.5 is not supported anymore by microsoft and azure...
It also gave me problems with visual studio 2022.

**Comment by Lakritzator** [comment]
Hey, thank you for your contribution!

I had a quick look, mainly looking at the change and ignoring the 4.5 error (I think we can drop the support).
What I am afraid of, is that this change partly fixes the issue, from what I found it doesn't work when a user has different DPI settings.

Instead of using the SystemParameters.SmallIconWidth and SystemParameters.SmallIconHeight it might make more sense to query them via: [GetSystemMetricsForDpi](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetricsfordpi) using [SM_CXSMICON](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getsystemmetrics)

This also means we need to pass the DPI for the screen where the icon is visible, I currently do not recall if we have that information at hand. I know I did do some DPI stuff, but I jump back and forth between projects...

**Comment by devpelux** [comment]
Maybe something likes that?
https://github.com/devpelux/fullcontrols/blob/fluent/FullControls/Core/Services/SysParams.cs

**Comment by Lakritzator** [comment]
Not exactly, as this doesn't use the Windows 10 APIs to get the current DPI.
But to be honest, I already added DPI information to the SystemInfo class.
See: https://github.com/hardcodet/wpf-notifyicon/blob/master/src/NotifyIconWpf/Interop/SystemInfo.cs#L76
I think a new ScaleWithDpi method for a Size would be good to have, than one could just use:

```
var iconSize = new Size((int)SystemParameters.SmallIconWidth, (int)SystemParameters.SmallIconHeight)).ScaleWithDpi();
return new Icon(streamInfo.Stream, iconSize.Width, iconSize.Height);
```

(untested code, don't have access to VS right now)

**Comment by devpelux** [comment]
I've added a way to get from CXSMICON and CYSMICON.
I don't know how to test for different DPI.

For me both the ways give me the same value

```
SystemInfo: {Width=16, Height=16}
SystemParameters: {Width=16, Height=16}
```

**Comment by Lakritzator** [comment]
I just noticed that you are targeting the master branch, which is not your fault but I guess we should make develop the default.

It doesn't make sense to target master (which reminds me that I wanted to rename it) please target develop, so you will not need to bring the code from develop over to master.

**Comment by Lakritzator** [comment]
Ah yes, I cannot change the default branch, there is that 🤷‍♂️ 

Hi @hardcodet, can you please change the default branch to develop, so the PRs we get do not go to older branches?

**Comment by hardcodet** [comment]
@Lakritzator  Done :)

**Comment by devpelux** [comment]
I don't have noticed the wrong branch, thanks for fixing.

**Pull request merged**
