### PR TITLE
Popup placement and offsets added

### PR DESCRIPTION
**Pull request by MaksymSlota**
Issue https://github.com/hardcodet/wpf-notifyicon/issues/25
1. Add ability to place popup not only near the mouse cursor.
2. PopupHorizontalOffset and PopupVerticalOffset added.
3. Show and close popup from code behind

### CODE REVIEW

**Comment by Lakritzator** [comment]
Hey cool, I'll need to look at this, this will take a bit.

**Comment by samhocevar** [comment]
This is great because it will make it easier fix a problem where navigating through the notification icons with <kbd>Windows</kbd><kbd>B</kbd> and the arrow keys currently shows the popup under the mouse cursor, wherever it is.

**Comment by Humple** [comment]
@Lakritzator Did you have a chance to review this changes? I need this feature for my project.

**Comment by samhocevar** [comment]
@MaksymSlota maybe you could merge the current `master` branch into this one so that your PR no longer has conflicts? I tested it and it merges gracefully.

**Pull request merged**
