### PR TITLE
Added .NET 5.0 and restructured the repository.

### PR DESCRIPTION
**Pull request by Lakritzator**
Continueing my work for dotnet core 3.1, I've now added .NET 5.0 support.
I'm actually not 100% sure if it really adds value which would motivate us to do an extra release for this, but as we didn't publish the dotnet core 3.1 support yet I guess it's good if we can do this in one go.

One clear advantage is that we can as least reproduce any issues with .NET 5.0, if needed.

I also renamed the samples to follow a more structured naming.

### CODE REVIEW

**Review by punker76 — APPROVED** [review]
LGTM 👍

**Comment by hardcodet** [comment]
Ping me before you release, so I can update the landing page accordingly in order to give you the credit for all the work you're putting into this :)

**Comment by Lakritzator** [comment]
We definitively need to make some release soon, we still didn't release the dotnet core 3.1 support and now there is already .NET 5.0 🤷‍♂️ 

But to be honest, I'm not sure about the added value of having a ".NET5.0-windows" package, besides visibility.

**Comment by sylveon** [comment]
I think not requiring users to build their own versions to use this in .NET 5 and .NET Core is pretty big added value

**Pull request merged**
