### PR TITLE
Add Support for targeting .NetCore 3.1

### PR DESCRIPTION
**Pull request by thudugala**
Support for targeting .NET Core 3.1

### CODE REVIEW

**Comment by Lakritzator** [comment]
I know it wasn't very visible, but there is already work done on dotnet core.
It's in a fork here: https://github.com/Lakritzator/wpf-notifyicon/tree/feature/dotnetcore3

Still it's nice to see other people putting in the work, I do have a few tips though:
* I don't think the maintainer likes that you just change his license.
* I would advice to ask if there is an interest before you put in the work.

**Comment by thudugala** [comment]
@Lakritzator revert back the licenseUrl

**Comment by punker76** [comment]
@thudugala This is now done with #21. Thanks anyway for your contribution. 👍

**Comment by thudugala** [comment]
Hope it will be published soon

**Pull request closed without merging**
